#!/bin/bash

rm -rf app-image-source
mkdir -p app-image-source/aaa

cat << "EOF" > app-image-source/aaa.desktop
[Desktop Entry]
Type=Application
Name=aaa
Exec=deno
Comment=Andy's AVR Assembler
Icon=aaa
Categories=Development;
Terminal=true
EOF

cat << "EOF" > app-image-source/AppRun
#!/bin/bash
APP_DIR=$(dirname $(readlink -f $0))
$APP_DIR/deno run --allow-read --allow-write $APP_DIR/aaa/cli.ts $@
EOF

convert -size 256x256 xc:white app-image-source/aaa.png
cp ~/bin/deno app-image-source

chmod u+x app-image-source/AppRun
chmod u+x app-image-source/deno

tar cf - --transform='s_/src/_/aaa/_g' ./devices/ $(
    find './src/' -type f | grep -v -e /examples/ -e test.ts -e testing.ts
) | (cd app-image-source ; tar xvf - )

# cSpell:words appimagetool
appimagetool-x86_64.AppImage app-image-source/
