#!/bin/bash

# cSpell:words deno biomejs

export DENO_DIR="$(pwd)/_deno"
mkdir -p "${DENO_DIR}"

TASK="${1:-run}"
case $TASK in
run)
    deno run -A ./src/cli.ts
    ;;
check)
    deno test --allow-read
    deno check -q $(find -name \*.ts | grep -v -e ./_deno/)
    deno lint
    ;;
report)
    rm -rf _coverage
    deno test --allow-read --coverage=_coverage
    deno coverage _coverage
    ;;
*)
    echo "./run [check|report|run]"
    exit 1
    ;;
esac
