import { assertEquals, assertFalse, assertNotEquals } from "assert";
import { des } from "./des.ts";
import { description, testEnvironment, testLine, Tests } from "./testing.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["", "DES", ["15"]], [15], ["number"], [0x94, 0xfb]]
];

Deno.test("DES Code Generation", () => {
    for (const test of tests) {
        const environment = testEnvironment();
        const translate = des(testLine(test[0], test[1], test[2]));
        assertNotEquals(translate, undefined);
        const result = translate!(environment.device.public);
        assertFalse(result.failed());
        assertEquals(result.code, [test[3]], description(test));
    }
});
