import { docTest, expectFileContents } from "../assembler/doc-test.ts";

Deno.test("serial-send Demo", () => {
    const demo = docTest();
    demo.source([
        '    {{ device("ATTiny2313"); }}',
        "    cli",
        "    clr R0",
        "    clr R1",
        "    dec R1",
        "",
        "setup_timer:",
        "    out TCCR1A, R0",
        "",
        "    ldi R18, (1 << CS12)",
        "    out TCCR1B, R18",
        "",
        "    ldi R18, high(1152)",
        "    out OCR1AH, R18",
        "    ldi R18, low(1152)",
        "    out OCR1AL, R18",
        "",
        "start_interval_timers:",
        "    out TCNT1H, R0",
        "    out TCNT1L, R0",
        "",
        "    ldi R18, (1 << OCF1A) | (1 << OCF1B)",
        "    out TIFR, R18",
        "",
        "setup_serial:",
        "    ldi R18, high(95)",
        "    out UBRRH, R18",
        "    ldi R18, low(95)",
        "    out UBRRL, R18",
        "",
        "    out UCSRA, R0",
        "",
        "    ldi R18, (1 << TXEN)",
        "    out UCSRB, R18",
        "",
        "    ldi R18, (1 << UCSZ0) | (1 << UCSZ1)",
        "    out UCSRC, R18",
        "",
        "the_top:",
        "    ldi ZL, low(digits_to_send << 1)",
        "    ldi ZH, high(digits_to_send << 1)",
        "",
        "send_digit:",
        "    out TCNT1H, R0",
        "    out TCNT1L, R0",
        "",
        "    ldi R18, (1 << OCF1A) | (1 << OCF1B)",
        "    out TIFR, R18",
        "",
        "wait_for_20ms_interval:",
        "    in R2, TIFR",
        "    sbrs R2, OCF1A",
        "    rjmp wait_for_20ms_interval",
        "",
        "get_next_char:",
        "    lpm R20, Z+",
        '    cpi R20, " ".charCodeAt(0)',
        "    breq the_top",
        "",
        "write_serial:",
        "    tst R20",
        "    breq send_digit",
        "",
        "buffer_wait:",
        "    sbis UCSRA, UDRE",
        "    rjmp buffer_wait",
        "",
        "    out    UDR, R20",
        "",
        "    rjmp send_digit",
        "",
        "digits_to_send:",
        '    {{ poke ("Testing1234 "); }}',
        ""
    ]);
    demo.assemble();
    expectFileContents(".lst").toEqual([
        "/var/tmp/demo.asm",
        "=================",
        '                      1     {{ device("ATTiny2313"); }}',
        "000000 94 F8          2     cli",
        "000001 24 00          3     clr R0",
        "000002 24 11          4     clr R1",

        "000003 94 1A          5     dec R1",
        "                      6",
        "                      7 setup_timer:",
        "000004 BC 0F          8     out TCCR1A, R0",
        "                      9",
        "                     10     ldi R18, (1 << CS12)",
        "                        mnemonic_unknown",
        "                        clue: LDI",
        "000005 BD 2E         11     out TCCR1B, R18",
        "                     12",
        "                     13     ldi R18, high(1152)",
        "                        mnemonic_unknown",
        "                        clue: LDI",
        "000006 BD 2B         14     out OCR1AH, R18",
        "                     15     ldi R18, low(1152)",
        "                        mnemonic_unknown",
        "                        clue: LDI",
        "000007 BD 2A         16     out OCR1AL, R18",
        "                     17",
        "                     18 start_interval_timers:",
        "000008 BC 0D         19     out TCNT1H, R0",
        "000009 BC 0C         20     out TCNT1L, R0",
        "                     21",
        "                     22     ldi R18, (1 << OCF1A) | (1 << OCF1B)",
        "                        mnemonic_unknown",
        "                        clue: LDI",
        "00000A BF 28         23     out TIFR, R18",
        "                     24",
        "                     25 setup_serial:",
        "                     26     ldi R18, high(95)",
        "                        mnemonic_unknown",
        "                        clue: LDI",
        "00000B B9 22         27     out UBRRH, R18",
        "                     28     ldi R18, low(95)",
        "                        mnemonic_unknown",
        "                        clue: LDI",
        "00000C B9 29         29     out UBRRL, R18",
        "                     30",
        "00000D B8 0B         31     out UCSRA, R0",
        "                     32",
        "                     33     ldi R18, (1 << TXEN)",
        "                        mnemonic_unknown",
        "                        clue: LDI",
        "00000E B9 2A         34     out UCSRB, R18",
        "                     35",
        "                     36     ldi R18, (1 << UCSZ0) | (1 << UCSZ1)",
        "                        mnemonic_unknown",
        "                        clue: LDI",
        "00000F B9 23         37     out UCSRC, R18",
        "                     38",
        "                     39 the_top:",
        "                     40     ldi ZL, low(digits_to_send << 1)",
        "                        mnemonic_unknown",
        "                        clue: LDI",
        "                     41     ldi ZH, high(digits_to_send << 1)",
        "                        mnemonic_unknown",
        "                        clue: LDI",
        "                     42",
        "                     43 send_digit:",
        "000010 BC 0D         44     out TCNT1H, R0",
        "000011 BC 0C         45     out TCNT1L, R0",
        "                     46",
        "                     47     ldi R18, (1 << OCF1A) | (1 << OCF1B)",
        "                        mnemonic_unknown",
        "                        clue: LDI",
        "000012 BF 28         48     out TIFR, R18",
        "                     49",
        "                     50 wait_for_20ms_interval:",
        "000013 B6 28         51     in R2, TIFR",
        "                     52     sbrs R2, OCF1A",
        "                        mnemonic_unknown",
        "                        clue: SBRS",
        "                     53     rjmp wait_for_20ms_interval",
        "                        mnemonic_unknown",
        "                        clue: RJMP",
        "                     54",
        "                     55 get_next_char:",
        "                     56     lpm R20, Z+",
        "                        operand_offsetNotLdd",
        "                        location.operand: 1",
        "                        mnemonic_unknown",
        "                        clue: LPM",
        '                     57     cpi R20, " ".charCodeAt(0)',
        "                        mnemonic_unknown",
        "                        clue: CPI",
        "                     58     breq the_top",
        "                        mnemonic_unknown",
        "                        clue: BREQ",
        "                     59",
        "                     60 write_serial:",
        "000014 23 44         61     tst R20",
        "                     62     breq send_digit",
        "                        mnemonic_unknown",
        "                        clue: BREQ",
        "                     63",
        "                     64 buffer_wait:",
        "                     65     sbis UCSRA, UDRE",
        "                        mnemonic_unknown",
        "                        clue: SBIS",
        "                     66     rjmp buffer_wait",
        "                        mnemonic_unknown",
        "                        clue: RJMP",
        "                     67",
        "000015 B9 4C         68     out    UDR, R20",
        "                     69",
        "                     70     rjmp send_digit",
        "                        mnemonic_unknown",
        "                        clue: RJMP",
        "                     71",
        "                     72 digits_to_send:",
        '000016 54 65 73 74   73     {{ poke ("Testing1234 "); }}',
        "000018 69 6E 67 31",
        "00001A 32 33 34 20",
        "                     74",
        "",
        "Symbol Table",
        "============",
        "",
        "buffer_wait = 21 (1) /var/tmp/demo.asm:64",
        "CS12 = 2 (1) /var/tmp/demo.asm:1",
        "digits_to_send = 22 (0) /var/tmp/demo.asm:72",
        "get_next_char = 20 (0) /var/tmp/demo.asm:55",
        "OCF1A = 6 (3) /var/tmp/demo.asm:1",
        "OCF1B = 5 (2) /var/tmp/demo.asm:1",
        "OCR1AH = 75 (1) /var/tmp/demo.asm:1",
        "OCR1AL = 74 (1) /var/tmp/demo.asm:1",
        "R0 (7) REGISTER",
        "R1 (2) REGISTER",
        "R2 (2) REGISTER",
        "R18 (18) REGISTER",
        "R20 (4) REGISTER",
        "send_digit = 16 (2) /var/tmp/demo.asm:43",
        "setup_serial = 11 (0) /var/tmp/demo.asm:25",
        "setup_timer = 4 (0) /var/tmp/demo.asm:7",
        "start_interval_timers = 8 (0) /var/tmp/demo.asm:18",
        "TCCR1A = 79 (1) /var/tmp/demo.asm:1",
        "TCCR1B = 78 (1) /var/tmp/demo.asm:1",
        "TCNT1H = 77 (2) /var/tmp/demo.asm:1",
        "TCNT1L = 76 (2) /var/tmp/demo.asm:1",
        "the_top = 16 (1) /var/tmp/demo.asm:39",
        "TIFR = 88 (3) /var/tmp/demo.asm:1",
        "TXEN = 3 (1) /var/tmp/demo.asm:1",
        "UBRRH = 34 (1) /var/tmp/demo.asm:1",
        "UBRRL = 41 (1) /var/tmp/demo.asm:1",
        "UCSRA = 43 (2) /var/tmp/demo.asm:1",
        "UCSRB = 42 (1) /var/tmp/demo.asm:1",
        "UCSRC = 35 (1) /var/tmp/demo.asm:1",
        "UCSZ0 = 1 (1) /var/tmp/demo.asm:1",
        "UCSZ1 = 2 (1) /var/tmp/demo.asm:1",
        "UDR = 44 (1) /var/tmp/demo.asm:1",
        "UDRE = 5 (1) /var/tmp/demo.asm:1",
        "wait_for_20ms_interval = 19 (1) /var/tmp/demo.asm:50",
        "write_serial = 20 (0) /var/tmp/demo.asm:60",
        "ZH (1) REGISTER",
        "ZL (1) REGISTER",
    ]);
});
