import { assertEquals, assertFalse, assertNotEquals } from "assert";
import { anEmptyContext } from "../../context/context.ts";
import { des } from "./des.ts";
import { description, testLine, Tests } from "./testing.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["", "DES", ["15"]], [0x94, 0xfb]]
];

Deno.test("DES Code Generation", () => {
    for (const test of tests) {
        const context = anEmptyContext();
        const translate = des(testLine(test[0]));
        assertNotEquals(translate, undefined);
        const result = translate!(context);
        assertFalse(result.failed());
        assertEquals(result.code, [test[1]], description(test));
    }
});
